### ISSUE TITLE
Do not limit the TicketSearch when exporting tickets (for 10.0 and later)

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/ImportExportTicket#10]
`TicketSearch() has a default limit of 10.000 tickets. This is no good for a complete export. As a workaround explicitly pass a limit of one billion which should cover all bases.

**Comment by bschmalhofer** [comment]
This is implemented for the branches rel-10_0, rel-10_1, and master (11.0). 

No closing the issue yet, as the changes have not been tested yet.

**Comment by bschmalhofer** [comment]
The same adaption needs to be done for the version in OTOBO 11.1.

**Comment by stefanhaerter** [comment]
Can this issue be closed?

**Comment by bschmalhofer** [comment]
@stefanhaerter Yes, this can be closed as it worked fine in a productive migration. I close it now.
